import express from "express";
import cookieParser from "cookie-parser";
import helmet from "helmet";
import cors from "cors";
import path from "node:path";
import { fileURLToPath } from "node:url";
import auth from "./routes/auth.js";
import chats from "./routes/chats.js";
import files from "./routes/files.js";
import providers from "./routes/providers.js";
import admin from "./routes/admin.js";
import { config } from "./config.js";
import { db } from "./db.js";

const __dirname=path.dirname(fileURLToPath(import.meta.url));
const app=express();
app.disable("x-powered-by");
app.use(helmet({crossOriginResourcePolicy:false}));
app.use(cors({origin:config.publicOrigin,credentials:true}));
app.use(express.json({limit:"2mb"}));
app.use(cookieParser());
app.get("/api/health",async(_req,res)=>{try{await db.query("SELECT 1");res.json({ok:true})}catch{res.status(503).json({ok:false})}});
app.use("/api/auth",auth);
app.use("/api/conversations",chats);
app.use("/api/uploads",files);
app.use("/api/providers",providers);
app.use("/api/admin",admin);
app.use(express.static(path.resolve(__dirname,"../../frontend")));
app.get("/{*splat}",(req,res)=>{if(req.path.startsWith("/api/"))return res.status(404).json({error:"API route not found"});res.sendFile(path.resolve(__dirname,"../../frontend/index.html"))});
app.listen(config.port,()=>console.log(`Internal AI Chat listening on ${config.port}`));
